"""add time_to_complete field to Tasks table

Revision ID: b93ffcc492bc
Revises: 7d6c6a7e625b
Create Date: 2024-07-07 16:55:50.779067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93ffcc492bc'
down_revision: Union[str, None] = '7d6c6a7e625b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('time_to_complete', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'time_to_complete')
    # ### end Alembic commands ###
